### ISSUE TITLE
compile error in node v10.20.1

### ISSUE THREAD

**Issue by DiamondYuan** [bevry/getmac#100]
```
docker run -it node:10 /bin/bash

git clone https://github.com/bevry/getmac.git

npm install 
npm run our:compile
```

![image](https://user-images.githubusercontent.com/9692408/80354825-d6a1cd00-88a9-11ea-984a-bb8b2e7ed9d0.png)

**Comment by marcoburrometo** [comment]
Same issue here!

**Comment by balupton** [comment]
looking into it

**Comment by balupton** [comment]
released to v5.2.0

**Comment by gogogo1024** [comment]
consider change this code
`
 const [key, parts] of Object.entries(list) 
`
change to
`
 const [_key, parts] of Object.entries(list) 
`
to fix typescript check error?

**Comment by balupton** [comment]
@gogogo1024 please make a new issue if there is a problem
