### ISSUE TITLE
Windows 8.1 gives "ERROR: Invalid class"

### ISSUE THREAD

**Issue by arthurakay** [bevry/getmac#12]
Attempting to use getMac() on Windows 8.1 throws "ERROR: Invalid class"

It seems something about the utility `getmac` is broken? I can't even run that in the Command Prompt.

**Comment by roccomuso** [comment]
still getting the error?

**Comment by balupton** [comment]
Not sure what this could be. However, I will convert it from CoffeeScript to JavaScript today, which should be a significant enough rewrite to fix this.

**Comment by hitsnorth** [comment]
Im getting the same error.. Windows 8.1 Invalid Class

**Comment by balupton** [comment]
This should have been fixed ages ago.
