### ISSUE TITLE
Does not recognize single-digit hex values

### ISSUE THREAD

**Issue by tigoe** [bevry/getmac#14]
The following hex value returns false from the isMac() function: 17:fc:34:fe:a5:e

Similarly, any address with a single digit in one byte value fails. I'd assume the code would read a single digit like the one above as 0e and succeed.

**Comment by balupton** [comment]
good catch, should fix

**Comment by balupton** [comment]
Please submit the command and the output of the command that produces such a MAC address

**Comment by balupton** [comment]
added support in v4.1
