### ISSUE TITLE
Doesn't build on webpack!

### ISSUE THREAD

**Issue by jsmankoo** [bevry/getmac#18]
the module child_process is causing issues with webpack, since there is no polyfill it can use

**Comment by balupton** [comment]
Are you anticipating this to run in a web browser? As MAC information is not available there, command line apps provide it, hence the neee for child process...

**Comment by jsmankoo** [comment]
I'm a moron. Thanks.

On Oct 11, 2016 11:13 AM, Benjamin Lupton <notifications@github.com> wrote:

Are you anticipating this to run in a web browser? As MAC information is not available there, command line apps provide it, hence the neee for child process...

**Comment by balupton** [comment]
Moron is pretty harsh. Mistakes don't make morons. We all make mistakes. You deserve kinder words. 🙏

🤔 What are you trying to do? Perhaps there is another way one can go about the problem. Do you need the MAC address of the server give to the web client, or a way to uniquely ID the web client, or was getmac just being loaded in webpack accidentally?

✌️️

**Comment by jsmankoo** [comment]
So I've been asked to create a login for a public web app that can only be accessed by company devices.
I thought if I can get client Mac addresses, I can hook them up with company accounts and setup it up that way.

On Oct 11, 2016 6:37 PM, Benjamin Lupton <notifications@github.com> wrote:

Moron is pretty harsh. Mistakes don't make morons. We all make mistakes. You deserve kinder words. 🙏

🤔 What are you trying to do? Perhaps there is another way one can go about the problem. Do you need the MAC address of the server give to the web client, or a way to uniquely ID the web client, or was getmac just being loaded in webpack accidentally?

✌️️

**Comment by jannhama** [comment]
Did you solve this already ? Can't you identify them by IP since they should come from company's server (proxy or vpn) ?

**Comment by balupton** [comment]
Please refer to the new readme section added in
https://github.com/bevry/getmac/commit/627005a37a1081891043209ff5f3cda5776f7927
