### ISSUE TITLE
Mac address on mobile devices

### ISSUE THREAD

**Issue by vinkrish** [bevry/getmac#21]
I'm asking this before going ahead and trying it out. Does it support Android, iPhone and Windows smartphones?

**Comment by balupton** [comment]
I've added a note to the readme of the underlying commands that getmac uses. I'm doubtful that they are available on the devices mentioned. However... if you can find any way of getting the mac address of those devices - perhaps via some command they provide that can be executed or even native code - happy to bundle them into getmac.

**Comment by balupton** [comment]
Please refer to the new readme section added in
https://github.com/bevry/getmac/commit/627005a37a1081891043209ff5f3cda5776f7927
