### ISSUE TITLE
'module cannot found 'child_process' error

### ISSUE THREAD

**Issue by lovepreet-virdi** [bevry/getmac#24]
there is issue in using the code of getting mac address in my application, but on cli it is working fine using getmac-node.
but using following code my getting the above error.
//////////////////////////////////////////code//////////////////////////////////
require('getmac').getMac(function(err,macAddress){
    if (err)  throw err
    console.log(macAddress)
})

**Comment by balupton** [comment]
Please refer to the new readme section added in
https://github.com/bevry/getmac/commit/627005a37a1081891043209ff5f3cda5776f7927
