### ISSUE TITLE
Angular 5 compatible version

### ISSUE THREAD

**Issue by abelardolg** [bevry/getmac#25]
Hi,
Is this library compatible with Angular 5?
If I would like to integrate into antoher application, how should I proceed with it?

According to the documentation, this library needs to run with 'Executable: getmac-node': how could I run with this instruction?

Kindest regards.

**Comment by mikeumus** [comment]
What's your server language? Hopefully, Node and then you can use the [`getMac()` API](https://github.com/bevry/getmac#api) and not worry about the executable. Otherwise you'll need an API endpoint on your server that calls a bash script or runs the `getMac-node` executable.

**Comment by balupton** [comment]
Perhaps we should state in the readme explicitly that this library is not for the client side.

**Comment by abelardolg** [comment]
@mikeumus , I am developing in the client side rather the server.

**Comment by abelardolg** [comment]
@balupton I thought this library could be used in the client side. :) :+1:

**Comment by mikeumus** [comment]
There you have it @abelardolg. You'll want to get access to the server side to execute this. One option for you might be a "server-less/cloud-function" approach where you don't need/manage a full web server/api. See: https://serverless.com/

**Comment by balupton** [comment]
Well. Using it on the server side wouls give the server’s mac address. I think most people wanting to use this on the client side are wanting to get their user’s mac address, which is impossible without getting them to install some software on their computer

**Comment by balupton** [comment]
Please refer to the new readme section added in
https://github.com/bevry/getmac/commit/627005a37a1081891043209ff5f3cda5776f7927
