### ISSUE TITLE
mac mi mini

### ISSUE THREAD

**Issue by north-fish** [bevry/getmac#303]
Error: failed to get the MAC address
![image](https://user-images.githubusercontent.com/15845160/130545832-b05e9e39-bac3-40e2-a895-15c94eb4a71e.png)

**Comment by balupton** [comment]
getmac v4 and higher have just been wrappers around https://nodejs.org/dist/latest-v12.x/docs/api/os.html#os_os_networkinterfaces

you should call that directly and see if it produces the results you need, then we can adapt this wrapper.

if that doesn't product the results you need, then you will need to file a bug report on the node.js issue tracker so they fix what that api returns
