### ISSUE TITLE
Error can't resolve OS

### ISSUE THREAD

**Issue by adilorenzodema** [bevry/getmac#306]
Hi, 
I installed getmac": "^5.20.0" for Angular 11,
and I have this error:

Can't resolve 'os' in '\node_modules\getmac\edition-es2019'

This is my use:
` 
import getMAC from 'getmac';

ngOnInit(): void {
    console.log(getMAC());
  }`

Can you help me please?

**Comment by balupton** [comment]
Can Angular run Node.js libraries?

**Comment by adilorenzodema** [comment]
No, it can't.

Yes not it's possible by client get the mac address of a web browser user.
