### ISSUE TITLE
in windows can't get mac by iface.

### ISSUE THREAD

**Issue by linevers1926** [bevry/getmac#32]
this code can solve：

command = isWindows ? "getmac /nh /v" : "ifconfig -a || ip link";   // add /nh /v

iface = new RegExp(`${iface}[:\\s]?`);   // add ?

**Comment by balupton** [comment]
Sure. Send a PR!

**Comment by linevers1926** [comment]
can you merge my branch into you master, i need use this code fix windoss when i npm install getmac

**Comment by balupton** [comment]
@linevers1926 please respond to https://github.com/bevry/getmac/pull/33#issuecomment-395238765

**Comment by balupton** [comment]
please try v4
