### ISSUE TITLE
Use in a Node.js Typescript project -- Could not find a declaration file for module 'getmac'

### ISSUE THREAD

**Issue by Homailot** [bevry/getmac#325]
I am trying to import this package into a typescript Node.js project. I have seen the section on the README about editions, but I can't select other editions when importing. I have tried the following, to no avail:

```typescript
import getMAC from 'getmac';
```

Results in `Could not find a declaration file for module 'getmac'.`

```typescript
import getMAC from 'getmac/source/index.ts';
```

Results in `Cannot find module 'getmac/source/index.ts' or its corresponding type declarations`

Do you have any suggestions or ideas about why I cannot import this? Thank you.

**Comment by balupton** [comment]
this should now be resolved with v6.2.0
https://github.com/bevry/getmac/commit/7e34b1ad039b830424cadde3ab089f71dd5e6411#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

shoutout to my [GitHub Sponsors](https://github.com/sponsors/balupton) for affording me the time to make this happen
