### ISSUE TITLE
Occasional garbled when getting mac on win7 32bit system

### ISSUE THREAD

**Issue by howiechow** [bevry/getmac#34]
uncaughtException,err.message:Command failed: C:\Windows\system32\cmd.exe /s /c "getmac"
????: ??????: δ??????????????????

 err.description:undefined err.number:undefined err.name:Error err.stack:Error: Command failed: C:\Windows\system32\cmd.exe /s /c "getmac"
????: ??????: δ??????????????????

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**************************************************************************************************************
version: 1.2.1

getMac = function(opts, next) {
  var command, data, extractMac, ref;
  ref = extractOptsAndCallback(opts, next), opts = ref[0], next = ref[1];
  data = opts.data;
  if (data == null) {
    data = null;
  }
  command = isWindows ? "getmac" : "ifconfig -a || ip link";
  extractMac = function(data, next) {
.......
  };
  if (data) {
    return extractMac(data, next);
  } else {
    return exec(command, function(err, stdout, stderr) {
      if (err) {
        return next(err);
      }
      return extractMac(stdout, next);
    });
  }
};

  command = isWindows ? "getmac" : "ifconfig -a || ip link";
   return exec(command, function(err, stdout, stderr)
maybe the error happend here? Has anyone encountered this problem?

**Comment by balupton** [comment]
please try v4
