### ISSUE TITLE
getmac does not return on Windows when group policy does not allow cmd access

### ISSUE THREAD

**Issue by sbatten** [bevry/getmac#41]
To test

1. Create a simple project with a main.js that just calls getmac and outputs the result
2. Disable running scripts via group policy
 - Run `gpedit.msc`
 - Navigate to `User Configuration > Administrative Templates > System`
 - Edit policy for `Prevent access to command prompt`
 - Enable the policy and say yes to sub-policy `Disable the command prompt script processing also?`
3. Use powershell to run `node main.js`

:bug: => the script will hang

Suggested fix:
Use execFile instead of exec to run `getmac.exe` instead of `%SystemRoot%\System32\getmac.exe` and pass the option `shell: false`

**Comment by balupton** [comment]
Sounds good to me. I will add support for execFile in the upcoming safeps version and post back later. Is it possible to get a bounty posted on this issue so it is funded? Will incentivise accomplishing it: https://discuss.bevry.me/t/bounty-donation-services/272?u=balupton

**Comment by balupton** [comment]
please try v4
