### ISSUE TITLE
Move @types/node to devDependencies

### ISSUE THREAD

**Issue by Hirse** [bevry/getmac#99]
As far as I can see the node type definitions are only required during development.
If that is the case, can they be moved to `devDependencies`?

**Comment by balupton** [comment]
Types should be installed to dependencies so developers consuming the package have access to the types. Only dev dependencies means the types are only installed the developers of our package, and not for developers consuming our package.

**Comment by balupton** [comment]
updated the above comment with further clarity

**Comment by Hirse** [comment]
Thanks for the update.

Afaik, it would only be necessary to include them in the dependencies if the types are part of the export.

Also, any project that uses types and this library would already have node type definitions as their own dependency.
